### ISSUE TITLE
Volt Dashboard - App Generator : ERROR

### ISSUE THREAD

**Issue by marc-odp** [app-generator/intro#23]
I received the following error : 
Status FINISHED
Task ID [c6d4010d-0190-4317-a082-2ae4d3982101]
Task is finished, result = FAILURE
cust_backend_db() err: file_load() takes 1 positional argument but 2 were given

My Options : FLASK - MYSQL - NO DEPLOYMENT

**Comment by app-generator** [comment]
Ty @marc-odp - we will get back once this flow is stable and tested.

**Comment by app-generator** [comment]
Hello @marc-odp, 

The reported issue has been fixed in the latest version **v0.0.8**.
All `Flask` use cases should be successful.
